name: PlatformIO CI + Test Check

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sep4_drivers
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/.cache
            ~/.cache/pip
          key: ${{ runner.os }}-platformio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
      - run: pip install --upgrade platformio

      - name: Build PlatformIO Project
      - run: pio test -e win_test
